### ISSUE TITLE
Title bar eats up full window height

### ISSUE THREAD

**Issue by erikjalevik** [Cristian006/frameless-titlebar#11]
I like the look of this library but when I try to add it to my application, the title bar is always taking up the full height of the whole application window.

I tracked it down in the debugger to some elements within the title bar having `height: 100%` set, while the top-level `div` has no explicit height set. If I manually set `height: 28px` to the top-level div in the debugger, everything looks fine.

I then figured maybe I needed to manually set the height in the theme, but that didn't work either:

```
<TitleBar
  app="Filur"
  menu={menuTemplate}
  theme={{
    barHeight: "28px",
    winBarHeight: "28px",
  }}
/>
```

What am I doing wrong? This is on Windows btw.

**UPDATE**: Just tried using plain numbers (e.g. 28 instead of "28px") in the theme object but it made no difference.

**Comment by Cristian006** [comment]
@erikjalevik I'm looking into it now.. I think it's an incorrect react version which I need to fix in the `package.json` since I use the React Context API to pass along the theme's properties.

What version of react are you using?

In the meantime, if you for example, use this boilerplate:
https://github.com/electron-react-boilerplate/electron-react-boilerplate

in the `main.dev.js` - make the window frameless
```js
  mainWindow = new BrowserWindow({
    show: false,
    width: 1024,
    height: 728,
    frame: false,
    titleBarStyle: 'hidden'
  });
```
remove the padding and margins from the body in the `app.global.css` file
```css
body {
  ....
  padding: 0px;
  margin: 0px;
}
```
and add the titlebar 
```bash
yarn add frameless-titlebar
```
In the `App.js` file include the Titlebar
```jsx
import TitleBar from 'frameless-titlebar';
...
   return (
      <React.Fragment>
        <TitleBar
          title="Titlebar"
          theme={{
            barTheme: 'dark',
            barBackgroundColor: 'rgb(36, 37, 38)',
            barColor: 'rgb(230, 230, 230)',
            menuHighlightColor: '#373277',
            menuDimItems: false,
            showIconDarLin: false
          }}
        ></TitleBar>
        {children}
      </React.Fragment>
    )
```

<img width="1468" alt="screen shot 2018-12-20 at 8 44 58 pm" src="https://user-images.githubusercontent.com/14713485/50325741-6f952c80-049b-11e9-883e-30bd64eab9d6.png">

Or have a look at the example folder in the project repository! :) I'll close this out when I update the project's `package.json`

**Comment by Cristian006** [comment]
@erikjalevik this commit https://github.com/Cristian006/frameless-titlebar/commit/ab87734baaff2925b927a35bf57717396a7a3844 should fix that 👍just make sure you update your `react` and `react-dom` version to 16.6.X and you should be good

**Comment by erikjalevik** [comment]
I now updated React to 16.7 and it all works fine.
