### ISSUE TITLE
Feature request: custom font on menus

### ISSUE THREAD

**Issue by erikjalevik** [Cristian006/frameless-titlebar#31]
Right now, I'm able to set the font of the title string via `titleFontFamily` in the theme, but it doesn't seem to affect the font of the menus.

It would be good to be able to set the font of both title and all menu strings to my application font.

**Comment by bjorn-nesby** [comment]
I agree, this would be a nice addition. With the option to not define any specific font (let the application decide).

Since I had the need to support aliased (jaggy) system fonts for my electron application, I had to come up with a workaround. It's simple enough: wrap your <TitleBar> in an element which include a css class (e.g. 'my-titlebar'), and, in your stylesheet, specify a rule such as the following 

```
.my-titlebar>div{
  font-family: "Segoe UI" !important;
}

```
