### ISSUE TITLE
importing the package throws `fs.existsSync` is not a function

### ISSUE THREAD

**Issue by danielkv** [Cristian006/frameless-titlebar#44]
![image](https://user-images.githubusercontent.com/5912401/59042397-c2e41700-8850-11e9-8beb-77477d07e642.png)

**Comment by IanMDay** [comment]
Same here.

**Comment by crazyjj** [comment]
Same too

**Comment by linwe2012** [comment]
same problem

**Comment by masoudmanson** [comment]
Same here, any solutions for this problem?

**Comment by linwe2012** [comment]
i replace `require` with `window.require` and it seems solve the problem.

**Comment by Cristian006** [comment]
@masoudmanson @linwe2012 @crazyjj @danielkv @IanMDay working on an update that will have a lot of improvements but, seems to be related to this issue https://github.com/electron/electron/issues/9920

**Comment by mr-tackie** [comment]
> 
> 
> i replace `require` with `window.require` and it seems solve the problem.

where exactly? Stuck here with the same issue

**Comment by mr-tackie** [comment]
Alright I finally managed to fix this. First of all make sure that your BrowserWindow options object has nodeIntegration set to true in the webPreferences object property
`window = new BrowserWindow({
...,
webPreferences: {
 nodeIngtegration: true
}
})`

and then edit the index.js/index.es.js files in frameless-titlebar in your node modules folder by changing `import electron, {remote} from 'electron'` to `const electron = window.require('electron');
const remote = electron.remote;
` 
Hope this issue is resolved in the next release of this plugin though. Thanks

**Comment by assimovt** [comment]
@Cristian006 I've got the same problem (`electron 7.1.7`). Do you happen to have any update ? Thx!

**Comment by zenith6495** [comment]
@mr-tackie thank you so so much man, it WORKED!! I've been stuck to this bug for so long!!! But seems like this issue happens commonly in React, Electron related packages as well, so I should do the same modifications to other packages if the same issue occurred?

**Comment by Cristian006** [comment]
@danielkv @assimovt @zenith6495 @mr-tackie @IanMDay @crazyjj @linwe2012 I know it's been a while but finally had some time to update the project, please try out v2 :) removed electron as a dependency which was causing several of these issues. 👌
